### ISSUE TITLE
demo.py unexpected keyword argument

### ISSUE THREAD

**Issue by Erickrus** [camenduru/Lumina-Next-jupyter#1]
```shell
Traceback (most recent call last):
  File "/content/Lumina-T2X/lumina_next_t2i_mini/demo.py", line 490, in <module>
    main()
  File "/content/Lumina-T2X/lumina_next_t2i_mini/demo.py", line 482, in main
    demo.queue().launch(
TypeError: Blocks.launch() got an unexpected keyword argument 'shasharre'
```
modify to share

**Comment by Erickrus** [comment]
With the default settings T4 card in ipynb, add `--use_flash_attn False`

**Comment by camenduru** [comment]
thanks ❤
